githubConfigUrl: "https://github.com/kumabes-org"
githubConfigSecret: gh-app-arc-community
maxRunners: 10
minRunners: 1
runnerGroup: "default"
runnerScaleSetName: "kumabes-runner-small"
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:2.318.0
        command: ["/home/runner/run.sh"]
        resources:
          limits:
            cpu: "0.5"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"