apiVersion: v1
kind: Service
metadata:
  name: nodejs-webapp
  labels:
    app: nodejs-webapp
spec:
  selector:
    app: nodejs-webapp
  ports:
    - protocol: TCP
      port: 80 ## port for service match port pod
      targetPort: 80  ## port in pod
      name: tcp-app
  type: ClusterIP
